"""add role

Revision ID: 73034ad69eb3
Revises: 249ec88d412f
Create Date: 2023-04-17 02:06:07.350890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73034ad69eb3'
down_revision = '249ec88d412f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
